---
# Variable configuration.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- name: Define mysql_daemon.
  set_fact:
    mysql_daemon: "{{ __mysql_daemon }}"
  when: mysql_daemon is not defined

- name: Define nginx_daemon.
  set_fact:
    nginx_daemon: "{{ __nginx_daemon }}"
  when: nginx_daemon is not defined

- name: Define mysql_port.
  set_fact:
    mysql_port: "{{ __mysql_port }}"
  when: mysql_port is not defined

- name: Define nginx_http_port.
  set_fact:
    nginx_port: "{{ __nginx_http_port }}"
  when: nginx_http_port is not defined

- name: Define nginx_https_port.
  set_fact:
    nginx_port: "{{ __nginx_https_port }}"
  when: nginx_https_port is not defined